DROP TABLE IF EXISTS bookmarks;
DROP TABLE IF EXISTS favorite_comments;
DROP TABLE IF EXISTS favorite_posts;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
